export declare const HTTP_ERROR_SUFFIX = " failed";
export declare const HTTP_SUCCESS_SUFFIX = " succeed";
export declare const HTTP_DEFAULT_TEXT = "request";
export declare const HTTP_DEFAULT_ERROR_TEXT: string;
export declare const HTTP_DEFAULT_SUCCESS_TEXT: string;
export declare const HTTP_ANONYMOUS_TEXT = "Who are U?";
export declare const HTTP_UNAUTHORIZED_TEXT_DEFAULT = "Unauthorized";
export declare const HTTP_PARAMS_PERMISSION_ERROR_DEFAULT = "Permission denied";
export declare const HTTP_BAD_REQUEST_TEXT_DEFAULT = "Unknown error";
export declare const VALIDATION_ERROR_DEFAULT = "Invalid params";
