
export const HTTP_ERROR_SUFFIX = '失败';
export const HTTP_SUCCESS_SUFFIX = '成功';
export const HTTP_DEFAULT_TEXT = '数据请求';
export const HTTP_DEFAULT_ERROR_TEXT = HTTP_DEFAULT_TEXT + HTTP_ERROR_SUFFIX;
export const HTTP_DEFAULT_SUCCESS_TEXT = HTTP_DEFAULT_TEXT + HTTP_SUCCESS_SUFFIX;

export const HTTP_DEFAULT_UNAUTHORIZED_TEXT = '权限验证失败';
export const HTTP_ANONYMOUSE_TEXT = '来者何人';